In [2]:
import torch
import numpy as np

In [ ]:
x = torch.empty(5,4)
print(x)

tensor([[1.8419e-34, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [ ]:
torch.rand(5,4)

tensor([[0.6998, 0.7517, 0.4188, 0.9277],
        [0.1900, 0.4845, 0.9006, 0.2534],
        [0.2368, 0.7100, 0.9834, 0.4290],
        [0.6495, 0.7941, 0.9825, 0.7143],
        [0.4473, 0.1359, 0.0329, 0.4636]])

In [ ]:
l = [13,4]
torch.tensor(l)             # 리스트를 텐서 타입으로 바꿔야 gpu연산 가능

tensor([13,  4])

In [ ]:
x.size()

torch.Size([5, 4])

In [ ]:
x=torch.rand(2,2)
print(x)
y=torch.rand(2,2)
print(y)
x+y

tensor([[0.9081, 0.4070],
        [0.7109, 0.9077]])
tensor([[0.6014, 0.4678],
        [0.2908, 0.8421]])


tensor([[1.5094, 0.8747],
        [1.0017, 1.7498]])

In [ ]:
torch.add(x,y)

tensor([[1.5094, 0.8747],
        [1.0017, 1.7498]])

In [ ]:
y.add(x)

tensor([[1.5094, 0.8747],
        [1.0017, 1.7498]])

In [ ]:
print('원래 y : ',y)
y.add_(x)
print('y=y+x : ',y)

원래 y :  tensor([[0.6014, 0.4678],
        [0.2908, 0.8421]])
y=y+x :  tensor([[1.5094, 0.8747],
        [1.0017, 1.7498]])


In [ ]:
# 텐서의 크기 변환

In [3]:
x = torch.rand(8,8)
print(x.size())
a = x.view(64)
print(a.size())

torch.Size([8, 8])
torch.Size([64])


In [4]:
print(x)
print(a)

tensor([[0.4859, 0.0402, 0.4123, 0.3621, 0.4434, 0.4751, 0.0539, 0.4489],
        [0.1823, 0.4305, 0.6986, 0.4371, 0.9314, 0.3254, 0.4855, 0.1227],
        [0.2287, 0.8988, 0.7870, 0.9018, 0.9583, 0.7859, 0.8002, 0.0986],
        [0.6050, 0.0631, 0.9085, 0.4287, 0.7791, 0.2567, 0.7600, 0.9946],
        [0.0745, 0.9862, 0.3215, 0.8277, 0.4741, 0.7190, 0.0784, 0.0527],
        [0.0547, 0.3433, 0.9598, 0.8350, 0.9410, 0.8366, 0.9596, 0.1422],
        [0.2957, 0.1196, 0.7138, 0.7820, 0.0898, 0.5299, 0.9444, 0.3215],
        [0.0175, 0.2126, 0.8013, 0.7033, 0.5159, 0.7659, 0.1739, 0.3672]])
tensor([0.4859, 0.0402, 0.4123, 0.3621, 0.4434, 0.4751, 0.0539, 0.4489, 0.1823,
        0.4305, 0.6986, 0.4371, 0.9314, 0.3254, 0.4855, 0.1227, 0.2287, 0.8988,
        0.7870, 0.9018, 0.9583, 0.7859, 0.8002, 0.0986, 0.6050, 0.0631, 0.9085,
        0.4287, 0.7791, 0.2567, 0.7600, 0.9946, 0.0745, 0.9862, 0.3215, 0.8277,
        0.4741, 0.7190, 0.0784, 0.0527, 0.0547, 0.3433, 0.9598, 0.8350, 0.9410,
       

In [5]:
b = x.view(-1,4,4)   # -1은 원래 크기가 되게 하는 값
print(b.size())

torch.Size([4, 4, 4])


In [6]:
b

tensor([[[0.4859, 0.0402, 0.4123, 0.3621],
         [0.4434, 0.4751, 0.0539, 0.4489],
         [0.1823, 0.4305, 0.6986, 0.4371],
         [0.9314, 0.3254, 0.4855, 0.1227]],

        [[0.2287, 0.8988, 0.7870, 0.9018],
         [0.9583, 0.7859, 0.8002, 0.0986],
         [0.6050, 0.0631, 0.9085, 0.4287],
         [0.7791, 0.2567, 0.7600, 0.9946]],

        [[0.0745, 0.9862, 0.3215, 0.8277],
         [0.4741, 0.7190, 0.0784, 0.0527],
         [0.0547, 0.3433, 0.9598, 0.8350],
         [0.9410, 0.8366, 0.9596, 0.1422]],

        [[0.2957, 0.1196, 0.7138, 0.7820],
         [0.0898, 0.5299, 0.9444, 0.3215],
         [0.0175, 0.2126, 0.8013, 0.7033],
         [0.5159, 0.7659, 0.1739, 0.3672]]])

In [ ]:
# 텐서에서 넘파이로
x = torch.rand(4,4)
y = x.numpy()
print(y)

[[0.7488372  0.38862878 0.8382356  0.6787401 ]
 [0.06078869 0.88139623 0.37383866 0.15295017]
 [0.90009224 0.43662268 0.59721315 0.43261635]
 [0.09907931 0.53789467 0.58193463 0.3004344 ]]


In [9]:
import torch
x=torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [10]:
y=x+1
z=2*y**2
res=z.mean()
print(y)
print(z)
print(res)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)
tensor([[8., 8.],
        [8., 8.]], grad_fn=<MulBackward0>)
tensor(8., grad_fn=<MeanBackward0>)


In [11]:
res.backward()


In [ ]:
print(x)
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[2., 2.],
        [2., 2.]])
